### ISSUE TITLE
Support IN

### ISSUE THREAD

**Issue by from81** [nackjicholson/aiosql#100]
Is it possible to write a query that contains `WHERE some_label IN (:labels)` and pass a list of string as labels?

Another question:
Is it possible to have an optional parameter?
For example, 
`SELECT * FROM cars WHERE brand = :brand AND year=:year;`
If the "year" variable is not passed, then it should become
`SELECT * FROM cars WHERE brand = :brand;`

**Comment by massyah** [comment]
for the IN operator, you can check #68
