### ISSUE TITLE
Any place to make donations?

### ISSUE THREAD

**Issue by midir99** [nackjicholson/aiosql#101]
This is an amazing library, I would love to support your wok via donations, is there a place I can do that?

**Comment by nackjicholson** [comment]
I don't need a new wok. :cook: Thank you.

No, there's no place to give donations, and I'm not taking them to work on this project. At this time, I'd encourage you to give donations to projects that this project relies on, or projects that the developers of this project rely on.

For me, that's things like Emacs, the FSF, the CNCF, Doom Emacs, Python, PostgreSQL, Psycopg2, SQLite, and Linux.
