### ISSUE TITLE
aiosql psycopg2 adapter is not escaping '%' in queries for psycopg2 driver

### ISSUE THREAD

**Issue by midir99** [nackjicholson/aiosql#102]
SQL queries loaded for driver `psycopg2` do not escape the character `%` 

[Documentation](https://www.psycopg.org/docs/usage.html#passing-parameters-to-sql-queries) of `psycopg2` states that in order to use the operator `%` in SQL queries, this must be escaped adding another percentage symbol:

```sql
%      <- not escaped
%%     <- correctly escaped
```
![image](https://user-images.githubusercontent.com/54189123/161347885-3e5d0936-0b84-4d52-9c5f-487252fb4caa.png)

You can test this behavior using the following code:
```python
import aiosql
import psycopg2

conn = psycopg2.connect("host=... port=5432 dbname=... user=... password=...")
stmts = """
-- name: get-module
-- This query obtains the module.
SELECT 5 % :num;
"""

queries = aiosql.from_str(stmts , "psycopg2")
module = queries.get_module(conn, num=2)
print(module)
```

This produces the following exception:

```
Traceback (most recent call last):
  File ".../qloader.py", line 74, in <module>
    module = queries.get_module(conn, num=2)
  File ".../venv/lib/python3.9/site-packages/aiosql/queries.py", line 63, in fn
    return self.driver_adapter.select(
  File ".../venv/lib/python3.9/site-packages/aiosql/adapters/psycopg2.py", line 24, in select
    cur.execute(sql, parameters)
TypeError: dict is not a sequence
```

That exception is the same that the one that occurs when executing a query with `psycopg2` without escaping the `%` character:
```python
import psycopg2

conn = psycopg2.connect("host=... port=5432 dbname=... user=... password=...")
cur = conn.cursor()
module = cur.execute("SELECT 5 % %(num)s", {"num": 2}).fetch_one()
print(module)
cur.close()
conn.close()
```

This produces the following exception:
```
Traceback (most recent call last):
  File ".../qloader.py", line 80, in <module>
    module = cur.execute("SELECT 5 % %(num)s", {"num": 2}).fetch_one()
TypeError: dict is not a sequence
```

**Comment by zx80** [comment]
Indeed. Same with `psycopg`.

A fix would involve somehow lexing the query, as you do not want to escape percent in a string or an ident. Lexing goes far beyond the scope of this tool. I'd suggest either to escape the operator manually, or to use the `MOD` SQL function.

I added a test, nevertheless.

**Comment by zx80** [comment]
Test pushed.
