### ISSUE TITLE
Pylance

### ISSUE THREAD

**Issue by PeterSanctus** [nackjicholson/aiosql#104]
Is there anyway, without making a wrapper function, to pylance recognises the queries names of the sql files when we are using them as methods in a Queries object? Because the code is "infested" with  "# type: ignore" comments.

thanks

**Comment by zx80** [comment]
My 0.02 €:

I understand that `pylance` is a VS-code specific type checker extension.

The point of `aiosql` is to generate SQL handling function dynamically, which is exactly against what a type checker wants to check for types.

**Comment by nackjicholson** [comment]
@PeterSanctus No way to do that easily.

You could make a python `typing.Protocol` that mirrors the shape of your queries object and then do something like the following where you type hint the queries object with your type.

```python
class YourQueriesProtocol(typing.Protocol):
    def get_user(id: int) -> Dict:
        ...

queries: YourQueriesProtocol = aiosql.from_path("./blah", ...)
```

Downside, anytime you add a new method or change an interface, you have to make a second mirroring change in your Protocol definition.
