### ISSUE TITLE
Taking this library to its full potential isn't something I've been able to do. Anyone else interested?

### ISSUE THREAD

**Issue by nackjicholson** [nackjicholson/aiosql#105]
I still think this project is great, and I'm so pleased that there are so many people who use it. However, when I began maintaining anosql, and then forked this project, I was a full-time software engineer with the time and focus to spend driving improvements to it. In the last 2-3 years my personal and professional circumstances have changed a lot. I've only been able to make sporadic commits a few times a year. I think it's time to admit to myself that for this project to grow and evolve, I can't be the person with the keys.

@seandstewart and @zx80 you two have been extremely helpful in keeping things moving somewhat. Are either of you in a position to drive this thing? I think we could probably keep it where it is for continuity, here on github. I would have to do a little bit of permissioning to make sure you have full access to change the CI stuff and to push new versions up to pypi. That's all possible to get done.

I think there is still lots of exciting work here, and I'm sure any new maintainer would find additional avenues for bettering aiosql.

Let me know your interest when you can.

**Comment by zx80** [comment]
Fine with me. I'm okay to share the burden as well!

**Comment by nackjicholson** [comment]
@zx80 Thanks Fabien. Send me your pypi.org username (or make an account if you don't have one).

**Comment by zx80** [comment]
Reopen. I did not intend to close the issue.

**Comment by zx80** [comment]
> @zx80 Thanks Fabien. Send me your pypi.org username (or make an account if you don't have one).

It's incredible, my `pypi.org` username is also `zx80`! :grin:

**Comment by nackjicholson** [comment]
@zx80 Okay, I added you to pypi.org as a maintainer. Let me know if that gives you everything you need. You are also a collaborator on this repository, with the ability to merge and make unilateral decisions.

I'm still available to you for anything you need. If you want to bounce ideas around I'll respond to emails. Feel free to ping me for advice or questions in issues or pull requests, I'll respond when I can. I still have systems running and using this library in production (though I'm actually a few versions behind), so I still have skin in the game here.

Here are my parting words as you take over.

Be good to the library and the community. Don't ship breaking API changes. Write good docs. Act with agency to replace anything you think I didn't get right, chances are I agree with you :) Be kind to any person who comes and makes an issue or asks a legitimate question, even if they're being rude. Don't ever feel like you have to do anything just because it was suggested or identified as a problem. Reserve the right to say no and disappoint people occasionally. You know best.

Reach out any time,
Will
