### ISSUE TITLE
Add support for 'fetchval' to return a single value.

### ISSUE THREAD

**Issue by xlevus** [nackjicholson/aiosql#11]
Asyncpg has a `fetchval` method that can be used to return a column from a single row. This is useful for queries such as getting the count.

e.g.
```sql
-- name: count_rows^
SELECT COUNT(*) FROM rows WHERE param = :value
```

requires the one of the python calls to get the value
```python
count, = queries.count_rows(value=1)
count = queries.count_rows(value=1)[0]
```

Whereas, if a notation for `fetchval` was supported only the following would be required:
```python
count = queries.count_rows(value=1)
```

**Comment by nackjicholson** [comment]
I think it would be a good improvement to have this supported directly, so please carry on! But, I'm not too bothered by the workarounds you showed unpacking the tuple either.

**Comment by nackjicholson** [comment]
Completed in the PR linked above.
