### ISSUE TITLE
Allow rebase merging?

### ISSUE THREAD

**Issue by zx80** [nackjicholson/aiosql#113]
@nackjicholson, could you enable "Allow rebase merging" in the project settings?

**Comment by zx80** [comment]
> @nackjicholson, could you enable "Allow rebase merging" in the project settings?

Hmmm… maybe it is already on, but by default Github generates a merge commit instead of a cleaner rebase commit.

**Comment by nackjicholson** [comment]
Hey Fabien,

It should already be on. I disabled merge commits as a "merge" button
option. Only rebase and squash now.

Best,
Will Vaughn
VP of Software, Carbon Lighthouse

**Comment by zx80** [comment]
Thanks!
