### ISSUE TITLE
Bug with % on PyFormatAdapter and PyMySQL

### ISSUE THREAD

**Issue by romkazor** [nackjicholson/aiosql#124]
Hello, some bug with %

```
aiosql==5.0
contextlib2==21.6.0
PyMySQL==1.0.2
```

queries.sql
```
-- name: get_now
SELECT NOW();


-- name: get_now_date
SELECT DATE_FORMAT(NOW(),'%Y-%m-%d %h:%i:%s');
```

```python
import os

import aiosql
import pymysql.cursors

queries = aiosql.from_path('queries.sql', driver_adapter='pymysql')

connection = pymysql.connect(
        host=os.environ.get('DB_HOST'),
        user=os.environ.get('DB_USER'),
        password=os.environ.get('DB_PASSWORD'),
        database=os.environ.get('DB_DATABASE'),
        cursorclass=pymysql.cursors.DictCursor
    )

with connection:
    print(queries.get_now(connection))
    print(queries.get_now_date(connection))
```

```
[{'NOW()': datetime.datetime(2022, 7, 28, 17, 44, 58)}]

  File "/opt/Project/env/lib/python3.10/site-packages/aiosql/queries.py", line 63, in fn
    return self.driver_adapter.select(
  File "/opt/Project/env/lib/python3.10/site-packages/aiosql/adapters/generic.py", line 23, in select
    cur.execute(sql, parameters)
  File "/opt/Project/env/lib/python3.10/site-packages/pymysql/cursors.py", line 146, in execute
    query = self.mogrify(query, args)
  File "/opt/Project/env/lib/python3.10/site-packages/pymysql/cursors.py", line 125, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string
```

**Comment by zx80** [comment]
Hmmm... The behavior of drivers around %-escaping is a pain :sob:

This case seems more or less tested, see `tests/blogdb/sql/blogs/blogs_mysqldb.sql`…

Does it work directly with the driver, i.e. without `aiosql`?

**Comment by romkazor** [comment]
> Does it work directly with the driver, i.e. without `aiosql`?

Without aiosql it's ok:

```python
with connection:
    with connection.cursor() as cursor:
        sql = "SELECT DATE_FORMAT(NOW(),'%Y-%m-%d %h:%i');"
        cursor.execute(sql)
        result = cursor.fetchall()
        print(result)
```

`[{"DATE_FORMAT(NOW(),'%Y-%m-%d %h:%i')": '2022-07-28 06:25'}]`

**Comment by zx80** [comment]
> "SELECT DATE_FORMAT(NOW(),'%Y-%m-%d %h:%i');"

ISTM that you dropped the `%s` which is one of C-format markers expected to be substituted by *format* paramstyle drivers... Is it ok with `%S` or `%s` as well?

**Comment by zx80** [comment]
Ok, I've found it after some effort to get a running `mysql` on my laptop (I do not do MySQL as a principle :grin:):.

This is because `aiosql` calls `execute` with an empty parameter list, and `pymysql` drivers does not like that and changes its behavior. Other MySQL drivers also have simular issues, although the messages are not the same.

```python
with connection:
    with connection.cursor() as cursor:
        sql = "SELECT DATE_FORMAT(NOW(),'%Y-%m-%d %H:%i:%S');"
        # this works if () is None
        cursor.execute(sql, ())
        result = cursor.fetchall()
        print(result)
```

Should fail miserably.

I'm unclear whether this is a driver misbehavior, but probably I should work around it anyway.

**Comment by zx80** [comment]
I've created an issue on [PyMySQL#1059](https://github.com/PyMySQL/PyMySQL/issues/1059) to have some feedback.

**Comment by zx80** [comment]
> I've created an issue on [PyMySQL#1059](https://github.com/PyMySQL/PyMySQL/issues/1059) to have some feedback.

The feedback is basically *won't fix* because every user can work around it :disappointed: :sob: :-1:

**Comment by zx80** [comment]
Work around for `pymysql` and `mysqldb` in 223517d.

**Comment by romkazor** [comment]
Thanks, can we fix GenericAdapter or make copy and fix cur.execute, it's solved problem:

```python
    def select(self, conn, _query_name, sql, parameters, record_class=None):
        cur = self._cursor(conn)
        try:
            cur.execute(sql, parameters or None)
            results = cur.fetchall()
            if record_class is not None and len(results) > 0:
                column_names = [c[0] for c in cur.description]
                results = [record_class(**dict(zip(column_names, row))) for row in results]
        finally:
            cur.close()
        return results
```

**Comment by zx80** [comment]
> Thanks, can we fix GenericAdapter or make copy and create new with fix cur.execute, it's solved problem:
 
I more or less did that with some inheritance. I do not want to change the behavior for the other drivers which do not need it. This is not a really a fix but a work around, IMO `pymysql` and `mysqldb` behaviors are wrong.

> ```python
>      parameters or None
> ```

Ah, I forget this trick!
