### ISSUE TITLE
add extent option to from_path

### ISSUE THREAD

**Issue by TomEubank** [nackjicholson/aiosql#145]
Currently `aiosql.from_path` can either open a single SQL file or scan a path
for multiple files.  When opening a single file, it is possible to specify a
filename extension (e.g., `.sqls`) to differentiate the file from other SQL
files, which usually contain a SQL script intended to be run from beginning
to end. However, when aiosql scans a path for SQL files, it can only look for
files with a `.sql` extension.

**Suggestion**: add an optional `ext='.sql'` argument to the `aiosql.from_path`
function definition, so that aiosql can scan for SQL scripts with a diffent
extension.

(I attempted to add this feature to my installed copy of aiosql, but couldn't
figure out how to pass the argument from `aiosql.from_path` to
`aiosql.query_loader.load_query_data_from_dir_path._recurse_load_query_data_tree`.  

So I improvised as follows in  `_recurse_load_query_data_tree`:

```
Original: 
               if p.is_file() and p.suffix != ".sql":
                    continue
                elif p.is_file() and p.suffix == ".sql":
As modified:
                _suffixes = ('.sql', '.sqls')
                if p.is_file() and p.suffix not in _suffixes:
                    continue
                elif p.is_file() and p.suffix in _suffixes:
```
This is definitely not an elegant solution, but it seems to be working for me.)

**Comment by zx80** [comment]
I do not really understand the motivation for this feature. It seems to me pretty reasonable to have `.sql` as an extension for SQL files? Editors rely on that for coloring and indenting, see `/etc/mime.types` on a Linux box for instance.

**Comment by zx80** [comment]
Added in 99623c391f3421561b60228dda387c803c72062f.
