### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by zx80** [nackjicholson/aiosql#154]
I wish to rename `master` to `main`. @nackjicholson, is this okay for you?

**Comment by zx80** [comment]
Actually It seems that cannot do it with the permissions I have.

@nackjicholson, could you either:
- do the renaming
- give me more permissions on the repos so that I can do it?

**Comment by nackjicholson** [comment]
![image](https://user-images.githubusercontent.com/365247/233202825-c1dafd00-6a03-4ad6-89af-b9c5ecc05ad6.png)
