### ISSUE TITLE
Some parsing bug regarding dash...

### ISSUE THREAD

**Issue by Oest1980** [nackjicholson/aiosql#156]
I try to query my database with the following where-clause:

...
WHERE sag.SagJournalNr LIKE "%" || :token || "%"

if :token equals "00.01.XX.Ø00-" I get the results I should get, but when I add something after the dash i.e.

if :token equals "00.01.XX.Ø00-0" I get no results back from the query, pointing to some parsing bug regarding the dash?

(I checked that it's not the Danish letters, that's the issue here.)

In another database I get the correct results using dash in the format: "010299-1020", making it extra weird...

**Comment by zx80** [comment]
What is the driver in use? If you perform the query directly, does it work?

**Comment by Oest1980** [comment]
to get queries I use: 

"aiosql.from_path(path, "aiosqlite")"

as connection I use:

"async with aiosqlite.connect(db_path) as conn:"

-------------------

yes, when I query the db directly in "DB Browser for SQLite" with the stored query, I get the correct results. When I query in python I get no results, as described above.

**Comment by zx80** [comment]
Hmmm... do you have a simple SQL script to reproduce the issue?

The `aiosqlite` adapter does nothing with the query, which is passed as-is to the driver, so the issue may be with the driver itself.

**Comment by zx80** [comment]
I could not reproduce the issue. Please reopen with a minimal script to reproduce it.

**Comment by Oest1980** [comment]
sorry to bring this up again, but just to explain what was going on: I realized, I made an error in my sql query, I used inner join where I should have used left join; inner join yielding zero results but left join giving me the expected results. You can delete this issue.

**Comment by zx80** [comment]
Issues are closed, not deleted.
