### ISSUE TITLE
pytest fails when importing aiosql

### ISSUE THREAD

**Issue by qs5779** [nackjicholson/aiosql#158]
app/db/queries/queries.py:3: in <module>
    import aiosql
/home/jim/.cache/pypoetry/virtualenvs/fastapi-realworld-example-app-ZyBE15IG-py3.10/lib/python3.10/site-packages/aiosql/__init__.py:7: in <module>
    import pkg_resources as pkg  # type: ignore
/home/jim/.cache/pypoetry/virtualenvs/fastapi-realworld-example-app-ZyBE15IG-py3.10/lib/python3.10/site-packages/pkg_resources/__init__.py:121: in <module>
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
E   DeprecationWarning: pkg_resources is deprecated as an API

[PR 157](https://github.com/nackjicholson/aiosql/pull/157) should rectify the issue.

As a work around I am running pytest with the "-W ignore::DeprecationWarning" argument.

FYI: Kudos on a very well designed package. This is one of the few contributions I was able to make and easily run the tests.

**Comment by zx80** [comment]
#157 merged into the dev branch.
