### ISSUE TITLE
Cant run test suite in dev mode without a local postgres instance

### ISSUE THREAD

**Issue by euri10** [nackjicholson/aiosql#16]
I found it annoying to have to install postgres on my dev machine just to run the tests, most of the time I'm using a throwaway docker container to do that.
The following PR https://github.com/nackjicholson/aiosql/pull/15 is an attempt at solving it.
For those who use a local instance it basically changes nothing, just need to run `POSTGRES_DSN=postrgres://.... pytest` instead of `pytest` and or those who don't have one they can chose to point the new var to wherever the db is.

**Comment by xlevus** [comment]
Have you seen:
https://pypi.org/project/pytest-postgresql/

**Comment by nackjicholson** [comment]
@euri10 Check out #40, it should allow you to run your tests without having postgresql installed.
