### ISSUE TITLE
Question: timeline for new release?

### ISSUE THREAD

**Issue by cofin** [nackjicholson/aiosql#167]
I have some code I'd like to port over to the integrated `duckdb` adapter once It's public on `pypi`.  Do you have a timeline for the next release?

**Comment by zx80** [comment]
Soon. Possibly this week or the next. I have to fix an issue with uploading to pypi because of sphinx extension.

**Comment by cofin** [comment]
Sounds great.  Thanks!

**Comment by zx80** [comment]
I made it, sorry for the delay. I had to work around a stupid issue with *pypi* blocking the upload because it was not happy with sphinx extension in `rst` files.
