### ISSUE TITLE
support sqlite RETURNING clause

### ISSUE THREAD

**Issue by EnigmaCurry** [nackjicholson/aiosql#170]
Currently the aiosql docs for the `<!` operator says this:

```
When using SQLite this operator will return the id of the inserted row using `cur.lastrowid <https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.lastrowid>`__.
```

Later on it mentions that only for postgresql will it return the actual value from the query. 

Well [sqlite now supports RETURNING](https://www.sqlite.org/lang_returning.html) too (implemented since version 3.35.0 2021-03-12), which it says is modeled directly after the postgresql feature, so I would like aiosql to return the value from the query, and not the rowid. But now it seems you might need to support the legacy way too, so a new method might be needed?

I would like to be able to run an `"upsert"` query like this one, which increments a number, saves it, and returns the new value, all in one query:

```
-- name: increment_user_greetings<!
-- Increment the number of times a user has been greeted
insert into greeting (name, times_greeted)
  values (:username, 1)
on conflict (name)
  do update set
    times_greeted = COALESCE(times_greeted, 1) + 1
  returning
    times_greeted;
```

Which, when using aiosql with sqlite, it returns the row id, not the times_greeted value. If I run the same query in DBeaver it returns the updated value.

**Comment by zx80** [comment]
Hmmm… actually you just have to remove the `<!` marker, as an explicit `RETURNING` is just like a regular `SELECT`?!

If okay, I think that a documentation clarification would be enough.

**Comment by EnigmaCurry** [comment]
Thank you, it took me awhile to wrap my head around the flexibility offered by the various operators. So the one I want for this query is actually `$` to return the single updated times_greeted count:

```
-- name: increment_user_greetings$                                                                                                            
-- Increment the number of times a user has been greeted                                                                                      
insert into greeting (name, times_greeted)
  values (:username, 1)
on conflict (name)
  do update set
    times_greeted = COALESCE(times_greeted, 1) + 1
  returning
    times_greeted;
```

Perhaps some more documentation about sqlite supporting RETURNING would be nice, but I'm satisifed! Thanks again.

**Comment by zx80** [comment]
Something done with #171
