### ISSUE TITLE
aiosqlite UPDATE! queries don't return rowcount

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [nackjicholson/aiosql#176]
I am running the latest version of `aiosql` and `aiosqlite`.
I have an UPDATE statement with `!` operator in a SQL file.

I notice that when running the generated function, it doesn't return the affected rows count.
However if I access the underlying cursor, I am able to obtain it.
Calling the same function using the built-in `sqlite3` driver without cursor also returns the rows count.

Attached a simple demo
[test.zip](https://github.com/nackjicholson/aiosql/files/13757596/test.zip)

**Comment by zx80** [comment]
Indeed. The behavior of async sqlite3 and postgres drivers is not the same, which is a pain.

**Comment by zx80** [comment]
I do not have much opinion about asynchronous features in python, it is a strange kind of weak parallelism, but python is so bad at parallelism that maybe it makes sense to do that for this scripting language.

Publish 9.2 attempts to do something about this particular issue.
