### ISSUE TITLE
ADBC Driver?

### ISSUE THREAD

**Issue by zachcp** [nackjicholson/aiosql#178]
Hi @nackjicholson ,

Than you for this great project - I am a fan of the yesql/hugsql approach. 

I am wondering how easy it might be to add an adapter for the Arrow Database Connectivity([ADBC](https://github.com/apache/arrow-adbc)) driver.  ADBC allows you to read/write from Databases that use column-stored data. It has a DB-API [compatible API](https://arrow.apache.org/adbc/current/python/driver_manager.html) so I would imagine that inheriting the existing methods wouldn't be too bad. But also a new Column-based Arrow representation which would need additional methods - e.g. `cursor.fetch_arrow_table()` which would return an Arrow array datastructure.

Would you be interested in a Pull request?
zach cp

**Comment by zx80** [comment]
Thanks for the suggestion.
I'm unclear about whether including this thing is or is not a good idea.
For now, I'm going to sleep in it, but keep the PL open.
