### ISSUE TITLE
Make CI require Py 3.12

### ISSUE THREAD

**Issue by zx80** [nackjicholson/aiosql#184]
@nackjicholson Will,

- could you turn the Python 3.12 as _required_ by GitHub CI ?
- Or give me access to the project settings?

Thanks in advance!

**Comment by zx80** [comment]
Pls...

**Comment by nackjicholson** [comment]
@zx80 I don't know how to give you more access than you already have on this repo. As is, where the repo is under my account the most I can make you is a collaborator. Perhaps if we made an organization and transferred the repo we'd have more optionality.

3.12 is now required. Let me know if that unblocks you.

**Comment by zx80** [comment]
Ok, thanks! We will see how it goes on the next updates.
