### ISSUE TITLE
OrderBy with asyncpg returns results but not sorted

### ISSUE THREAD

**Issue by sylvainmouquet** [nackjicholson/aiosql#188]
Hello,

In sql file, i use
```
ORDER BY
  :orderBy
```
and in python
`orderBy = f"{sortBy} {order}"`

The query is executed but the results do not follow the sort order.
If I define the order by without parameter, it works.

The error is in aiosql side or in asyncpg ?

**Comment by sylvainmouquet** [comment]
The response is here : https://stackoverflow.com/a/12430474/592348
it's not possible to use parameter values for sort column and sort order

**Comment by zx80** [comment]
Indeed, this is a limitation of the underlying SQL driver.
