### ISSUE TITLE
Please remove rules about required status checks?

### ISSUE THREAD

**Issue by zx80** [nackjicholson/aiosql#197]
Hello @nackjicholson 

I had a PR action which just failed, but the error message reminded me that I'm sometimes blocked to maintain AioSQL because I do not have enough permissions, in particular I do not have even read access to the project settings.

Could you, if possible, give me "admin" or whatever permissions so that I can access the settings? Ok, I'm unsure that it is possible with GitHub on the free version...

If not, could you REMOVE the rule about required CI passes (probably named "Require status checks to pass")? Every year there is one new Python release and one Python version is dropped for maintenance, it seems unhelpful to have to edit this list constantly to change the required versions, and I cannot do it. Or maybe only require "python latest" if possible? I cannot see what the settings are, so I'm unclear about what to suggest, but a complete removal of the rule would probably work, and probably I would not force a PR with a failing test unless there is a good reason for that.

Thanks in advance.

@zx80

**Comment by nackjicholson** [comment]
@zx80 I removed all the required checks. Let me know if that gives you what you need. If not, I will fiddle with it more. As discussed in the past, I can't give you more access unless we create a github organization.
