### ISSUE TITLE
Could I drop support for python 3.6?

### ISSUE THREAD

**Issue by nackjicholson** [nackjicholson/aiosql#31]
#29 This came up, dataclasses aren't usable in this library until we support 3.7+

Worse is the [aioctxlib.py](https://github.com/nackjicholson/aiosql/blob/master/aiosql/aioctxlib.py) hack I wrote to get around not having this [contextlib.asynccontextmanager](https://docs.python.org/3/library/contextlib.html#contextlib.asynccontextmanager) in < 3.7

I think this library being a target for users of asyncio and modern versions of python gives me a pretty good reason to not support 3.6 if it's becoming inconvenient. Asyncio itself went through major changes from 3.6 to 3.7 and people should update asap for that.

**Comment by alecbrooks** [comment]
Two things that might impact this decision:
* Python 3.6 is only receiving [security fixes][security] and will be at end of life in December 2021.
* Anosql was deprecated [yesterday][yester].

Aiosql seems pretty stable and feature-complete already, so I don't think focusing future development efforts on 3.7+ is going to cause problems for people who can't yet upgrade from 3.6.

[security]: https://devguide.python.org/#status-of-python-branches
[yester]: https://github.com/honza/anosql/commit/903d82f7bc00a97452527c6804054ee931cae03c

**Comment by nackjicholson** [comment]
@alecbrooks Thanks for letting me know about these things. Also, thank you for weighing in with an opinion!

**Comment by dlax** [comment]
Python 3.6 is still the only option when using with RedHat/CentOS (from version 7 or 8). I know this is annoying, but many people working with databases (at least postgresql) are "stuck" with such systems. As a comparison, [psycopg3](https://github.com/psycopg/psycopg3) supports python 3.6 while explicitly targeting asyncio.

**Comment by nackjicholson** [comment]
@dlax Thank you that's a very good point. I recently used python on Centos 8 with python 3.6. It is something to consider. I think @alecbrooks made a point that makes me feel like we're not leaving users of python 3.6 without an option. The lib still supports 3.6 on this current major version. I think I'd like to shore up some loose ends, make this version as mature as possible and then make a major version bump that drops 3.6.

I'm still not decided on if I'm going to do it or not. Just thoughts.

**Comment by dlax** [comment]
Alternatively, we could require python >= 3.7 only for some modules
(adapters). That would solve the issue with contextlib.asynccontextmanager.

**Comment by nackjicholson** [comment]
@dlax I'd be interested in doing that. How do I do that? :D

**Comment by dlax** [comment]
> I'd be interested in doing that. How do I do that? :D

See #48 for a possible solution.

**Comment by nackjicholson** [comment]
@dlax I see, thanks for that!

I think I need to think about this a little more. There's some other api changes I want to play with for a version 4, chiefly around changing `record_class` to something that can both marshal data in, as well as out. With that major bump it seems I'll also need to make a decision on the manner in which to support py3.6. What you did there still demands a major version bump because it takes away async drivers for people on 3.6. it makes me think maybe the hack I did for the async context manager isn't the worst thing I could've done, it lets me support 3.6 fully. I wonder if there's a more "official" backport of it available on pypi or something. Its not ideal to support two different sets of functionality for different versions of python, that seems like it could cause people confusion about the library and be troublesome to debug and develop around for us.

Here's the options I'm seeing now for py3.6:

1. Drop it entirely from a version 4, point people back to a pretty mature final version of version 3 if they really need to be on version 3.6.
2. Support py3.6 but only for sync drivers, take your changes in #48
3. Fully support py3.6 for all drivers, keep the hack, or find a better one. 

Thanks for the discussion! Let me know what you think about all that.

**Comment by nackjicholson** [comment]
https://github.com/python-trio/async_generator

**Comment by dlax** [comment]
@nackjicholson, thanks for your feedback.

I agree using a more "official" backport would be nicer (and clearer to end users) than the hack in aioctxlib (which is at the moment kind of hidden to the end user of the library). There is also a discussion to add asynccontextmanager to contextlib2: https://github.com/jazzband/contextlib2/issues/12.

> There's some other api changes I want to play with for a version 4, chiefly around changing record_class to something that can both marshal data in, as well as out.

Is this related to the dataclass subject mentioned earlier? Is there an issue explaining this?

**Comment by nackjicholson** [comment]
> Is this related to the dataclass subject mentioned earlier? Is there an issue explaining this?

Unrelated, I just said this as an aside. Also, to let you know I'm already thinking about doing a major version bump at some point.  The marshal in / marshal out part is an evolution of my thinking on `record_class`, which has been a feature I've sort of regretted having in its current form. #12 is the closest thing to an explanation.

**Comment by nackjicholson** [comment]
Looking like contextlib2 might be ready for use on 3.6 now

**Comment by nackjicholson** [comment]
#65
