### ISSUE TITLE
column names?

### ISSUE THREAD

**Issue by jimmyshah** [nackjicholson/aiosql#33]
Hi! Is there any way to get the column names from a query? I browsed the docs, but didn't seem to find anything...

**Comment by nackjicholson** [comment]
If you're using a select query you can add `_cursor` to the end of your query name you can get the raw database cursor. This is your escape hatch to do anything you can do with the normal db cursor.

```python
with queries.my_query_cursor(conn) as cur:
    print(cur.description)
    for row in cur.fetchall():
        print(row)
```

There's a section still largely unwritten on advanced topics. The section you're looking for still just says "TODO"

https://nackjicholson.github.io/aiosql/advanced-topics/#access-the-cursor-object

**Comment by nackjicholson** [comment]
I'm going to leave this open so others can read this issue easily. We'll see if someone has time to contribute docs to cover this. If not, I'll mark it as a todo for myself.

**Comment by MichelCarroll** [comment]
@nackjicholson I can grab this one, if you don't mind. 

Is there any particular way you saw the columns being exposed? I was thinking of adding another property to the query object. For example: 
`queries.my_query.columns`

**Comment by nackjicholson** [comment]
@MichelCarroll I haven't considered exposing columns at all. I'm not sure I would. How are you adding them as a property of the query function?

I think what I want from the docs is to let people know that they have an escape hatch to the underlying database cursor should they need it, and this helps them workaround limitations of aiosql. I don't want aiosql to have to support every possible usage of a database query. I want it to easily cover the basics, and not make everything else hard.

Here are things I've personally done with the `_cursor`.

I used it before we had a select_value operator `$` in order to do that myself.

```python
queries.my_query_cursor(conn, **kwargs) as cur:
    res = cur.fetchone()
    if not result:
        raise Exception("blah")
    return result[0]
```

Boom! Instant work-around for a missing feature.

I think https://nackjicholson.github.io/aiosql/advanced-topics/#accessing-prepared-sql-as-a-string this little hack I put in the docs is a similar type of "feature" for aiosql. You don't even have to use aiosql to execute your query, we give you an out to just use the loaded sql string.

```python
# Do whatever you want, however you want. Don't even call through to our methods.
# I trust you and I'm trying to stay out of your way!
with conn.cursor() as cur:
    res = cur.execute(queries.my_query.sql, params)
```

**Comment by MichelCarroll** [comment]
@nackjicholson Good points. I hadn't really considered it that way.

I think you have a much better idea than me of how you want to explain the use of the `*_cursor` escape hatch, so I'll let you take care of it.

**Comment by danmurphy1217** [comment]
@nackjicholson- happy to help write the documentation for this if it is still needed. I've been interested in contributing to aiosql, and this seems like a good way to better introduce myself to the codebase. Let me know your thoughts.

**Comment by nackjicholson** [comment]
@danmurphy1217 Go for it! Welcome!

**Comment by polyrand** [comment]
One option can be combining aiosql with [encode/databases](https://github.com/encode/databases). It relies on sqlalchemy so you can use [RowProxy](https://docs.sqlalchemy.org/en/13/core/connections.html#sqlalchemy.engine.RowProxy) or the native [Record](https://magicstack.github.io/asyncpg/current/api/index.html#record-objects) object of asyncpg.

This is something I've implemented for an app that's going to production:

```python
# import databases
# connecto to DB
# ... etc 
# 
# don't process the sql since sqlalchemy/databases 
# expects `:` for variable names in the query
# note: the aiosqlite adapter also works and does the same thing
class RawSqlAdapter:
    is_aio_driver = True

    @staticmethod
    def process_sql(_query_name, _op_type, sql):
        """Pass through function."""
        return sql

queries = aiosql.from_path("queries.sql", driver_adapter=RawSqlAdapter)

user = await database.fetch_one(queries.user_get_by_email.sql, {"email": email})

# now you can use the proxies provided by sqlalchemy/asyncpg
# to do somthing like

user_id = user["user_id"] # or whatever is the column name
```

I like the approach taken by @nackjicholson of keeping aiosql very "raw" and not adding ORM features.

(I'm planning to write a mix of aiosql + asyncpg Record objects + dataclasses/pydantic wrapper to get an ORM'ish behavior without using and ORM, but I don't know how that will turn out).

Even though it relies on [encode/databases](https://github.com/encode/databases). If the example I provided above is considered useful, I could write it with more detail and add it to the aiosql docs.

**Comment by nackjicholson** [comment]
#49
