### ISSUE TITLE
Allow comments in SQL files

### ISSUE THREAD

**Issue by zx80** [nackjicholson/aiosql#35]
It is really convenient to allow misc SQL comments in the SQL file loaded. With something like:

```SQL
    -- SQL queries...

    -- name: one
    SELECT 1;
```

I got `aiosql.exceptions.SQLParseException: name must convert to valid python variable, got "__ SQL queries".`

**Comment by nackjicholson** [comment]
Thanks for reporting! I imagine that can be fixed. I'll be away for a few weeks though FYI.

**Comment by nackjicholson** [comment]
https://github.com/nackjicholson/aiosql/commit/9c3cc26449fdfc4a8a4aec2f98a131d953ef75ee Addressed! @zx80
