### ISSUE TITLE
pip vs poetry

### ISSUE THREAD

**Issue by zx80** [nackjicholson/aiosql#37]
ISTM that it would be convenient to make `pip` installations work instead of requiring `poetry`, which would suggest to provide a basic `setup.py` file, which is probably needed anyway for `pypi`.

Is there a special reason not to provide that file in the repos?

**Comment by nackjicholson** [comment]
This tool might help, maybe we can make it automatic. https://github.com/dephell/dephell

A lower lift way of doing it might also be to use `poetry export` in order to create a requirements.txt and then have a fairly simple setup.py that we commit to the repo that generates it's dependencies off of that. What I don't want to do is manage the pyproject.toml and a separate requirements.txt or setup.py. I want to keep use one thing and have everything else just work. Right now that one thing is poetry.

**Comment by zx80** [comment]
> This tool might help, maybe we can make it automatic. https://github.com/dephell/dephell

Yet another tool and dependency, exactly what I'm trying to avoid :disappointed: 

> A lower lift way of doing it might also be to use `poetry export` in order to create a requirements.txt and then have a fairly simple setup.py that we commit to the repo that generates it's dependencies off of that. What I don't want to do is manage the pyproject.toml and a separate requirements.txt or setup.py. I want to keep use one thing and have everything else just work. Right now that one thing is poetry.

Hmm… The point is to automate things as much as possible: if one has to think of regenerating stuff by hand before committing and pushing, this is simply error prone and unfriendly.

I tried to write a `setup.py` which just reads the `toml` file to extract the relevant information. See [pull request](https://github.com/nackjicholson/aiosql/pull/38).

**Comment by nackjicholson** [comment]
Poetry deploys using wheels, it doesn't need the setup.py to deploy to pypi. I'll take a look at your PR, building the setup.py off of the deps listed in the `toml` seems like a good approach.

**Comment by seandstewart** [comment]
pip no longer requires setup.py either, and can install directly from `pyproject.toml` as well: https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support

**Comment by nackjicholson** [comment]
I'm closing this. Even though I really like the poetry project and use if for production work projects, I stopped using it in aiosql. The dependency management for this project isn't complicated. There is one required shim library `typing_extensions` and a handful of pretty basic dev dependencies to the power the tests and linting. Using `setup.py` and `setup.cfg` keeps things simple and familiar for anyone who would want to contribute to aiosql.

You can read more about the changes I made recently below:

https://github.com/nackjicholson/aiosql/blob/master/docs/contributing.md
