### ISSUE TITLE
Multiple statements don't work

### ISSUE THREAD

**Issue by ccann** [nackjicholson/aiosql#39]
```mysql
-- name: up#
CREATE TABLE foo
(
	id VARCHAR(255) PRIMARY KEY
);

CREATE TABLE bar
(
	id VARCHAR(255) PRIMARY KEY
);
```
> pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE bar\n(\nid VARCHAR(255) PRIMARY KEY\n)' at line 6")

This only works if I make the second `CREATE TABLE` its own method.

The only caveat is that I'm using a custom DB adapter for (synchronous) MySQL which is pretty much a copy-paste of the psycopg2 adapter you have here with `conn.commit()` added to the `insert` methods.

**Comment by ccann** [comment]
Actually, my mistake, I didn't know I had to set `client_flag` to `pymysql.constants.CLIENT.MULTI_STATEMENTS` in order to enable multiple statements.

**Comment by nackjicholson** [comment]
@ccann Glad you figured it out. Glad the DB Adapter worked for you. If you want to contribute a PR with that adapter I'll at least read it over. Not sure if I want to take on having more officially "blessed" driver adapters in the repo or not, but a PR and some example code/discussion could be really helpful to anyone else that comes along looking to use pymysql and aiosql.
