### ISSUE TITLE
Difference between aiosql and anosql?

### ISSUE THREAD

**Issue by anthonydb** [nackjicholson/aiosql#41]
Hi, I just noticed the deprecation of anosql and, having not used it or aoisql yet, I was wondering what the differences are between the two libraries, if any?

**Comment by nackjicholson** [comment]
@anthonydb aiosql is a fork of anosql. I kept them very similar for a long time. In short aiosql is usable with asyncio based database drivers. And aiosql is only usable on python versions >= 3.6.

**Comment by anthonydb** [comment]
OK, cool! I'm going to find a project to try this on soon. All the best.
