### ISSUE TITLE
How to connect to MySQL or MariaDB?

### ISSUE THREAD

**Issue by gudata** [nackjicholson/aiosql#44]
Hello,
What is the way to connect to MySQL? I tried this way but I got an error.

```
import aiosql
import pymysql

connection = pymysql.connect(
    host="data-mysql-rds.example.com",
    user="root",
    password="******",
    db="db",
    charset="utf8",
)


queries = aiosql.from_path("./sql", "pymysql")
# ValueError: Encountered unregistered driver_adapter: pymysql
queries = aiosql.from_path("./sql", connection)
# TypeError: 'Connection' object is not callable
```

**Comment by nackjicholson** [comment]
You need to create a driver adapter for pymysql. https://nackjicholson.github.io/aiosql/database-driver-adapters/

This question has come up before. #24 I encourage anyone who needs this to create a driver adapter and opensource it. If it were a project called aiosql-mysql I would certainly link to it from the README here.

If someone wants to figure out how to do asyncio and sync adapters for MySQL I would consider adding it to this project as officially supported.

Same goes for MariaDB using the underlying https://github.com/mariadb-corporation/mariadb-connector-python driver.

**Comment by abbazs** [comment]
The following URL return page is not found.
> https://nackjicholson.github.io/aiosql/database-driver-adapters/

**Comment by nackjicholson** [comment]
@abbazs https://nackjicholson.github.io/aiosql/database-driver-adapters.html

**Comment by nackjicholson** [comment]
Closed because people should try out the library shared in #79 .
