### ISSUE TITLE
Quicker named parameters

### ISSUE THREAD

**Issue by BrendanMartin** [nackjicholson/aiosql#5]
For named parameter queries like this:

```
-- name: bulk-publish*!
-- Insert many blogs at once
insert into blogs (
    userid,
    title,
    content,
    published
)
values (
    :userid,
    :title,
    :content,
    :published
)
```

It seems redundant to me to have to type the columns out twice. Perhaps there's a way to automatically fill the values to the default column names when loading the queries?

**Comment by nackjicholson** [comment]
Hmmm, but that's the way SQL is written. This library certainly can't change that (and probably shouldn't!)

Even if I did know how to do what you're asking for, I don't think it would be a good idea to get into the business of changing the sql syntax. This library is to help you write SQL in .sql files and use it from your python code, it is not here to make writing SQL more ergonomic.

Thanks for the thought, and thanks for using the library.

**Comment by BrendanMartin** [comment]
Oh I see. I was thinking that the library had done something with the query itself. I was thinking it would be neat to just do something like: 
```
-- name: bulk-publish*!
-- Insert many blogs at once
insert into blogs (
    userid,
    title,
    content,
    published
)
values (*)
```
And the * is automatically expanded.

Anyway, thanks for the library!
