### ISSUE TITLE
How to substitute the columns you want to select in a query

### ISSUE THREAD

**Issue by codyflynnNC** [nackjicholson/aiosql#50]
For example: 
```
-- name: get-orders-dynamic
SELECT {columns}
FROM orders
WHERE store = :store  and product = :product;
```
where `columns = 'store_name, store_id'` etc.. 

is this possible through aiosql?

**Comment by nackjicholson** [comment]
@codyflynnNC No, it's not currently possible. Possibly related to #21

**Comment by codyflynnNC** [comment]
Yep definitely related - I'll close this issue in favor of the linked one above.
