### ISSUE TITLE
Off-by-one on AsyncPGDriverAdapter.var_replacements

### ISSUE THREAD

**Issue by seandstewart** [nackjicholson/aiosql#51]
**aiosql version:** 3.2.0
**Python version:** 3.8

### Description

First of all, thanks for maintaining such an excellent library. I've been itching for a chance to use it for a while now and finally have the opportunity.

I've come across an issue where if there are multiple child query clients with similar parameters, the `AsyncPGDriverAdapter` will not properly count them when processing the SQL file.

The issue appears to be isolated to this block:

https://github.com/nackjicholson/aiosql/blob/f2095151d6601eed49ae29e45e37e30e0f67ca0c/aiosql/adapters/asyncpg.py#L40-L46

If there are multiple queries with the same name which share an argument with the same name, the count will not be incremented when that var name is replaced.

There are two issues with this: 
1. All queries with the same name must implement matching arguments in exactly the same order. (Easily worked with)
2. Subsequent queries' additional arguments will all be off-by-one. (Breaks this use-case)

### Proposed solution

I think the simplest solution would be to namespace the keys in `var_replacements` with the query source as well as name. This would prevent argument collision from occurring at all.

### Current Workaround

My current workaround is to load each query directory individually. This works for my use-case, but is still a bit of a gotcha.

**Comment by nackjicholson** [comment]
@seandstewart Thanks for reporting this!

**Comment by nackjicholson** [comment]
@seandstewart When you have a moment could you provide an example of sql you're loading that would cause this problem? If so, I think it would be very helpful.

Thank you very much for your thoughtful description of the problem. Greatly appreciated

**Comment by seandstewart** [comment]
Hey @nackjicholson - sorry for the delay in response, work's been crazy, then I was on holiday for a week. Essentially:

A directory structure like:
```
queries/
  bar/
    lib.sql
  foo/
    lib.sql
```

With the following SQL files: 

```sql
-- foo/lib.sql

-- name: search
-- Get a row from foo by name and value
SELECT * from foo WHERE name = :name and value = :value
```

```sql
-- bar/lib.sql

-- name: search
-- Get a row from bar by name and result
SELECT * from bar WHERE name = :name and result = :result
```

Would result in:

`foo/lib.sql::search` => `SELECT * from foo WHERE name = $1 and value = $2`
`bar/lib.sql::search` => `SELECT * from bar WHERE name = $1 and result = $1`

**Comment by nackjicholson** [comment]
@seandstewart Hey, no worries. Work is pretty crazy for everyone right now I imagine. I know I'm feeling that too. Thanks very much for getting back to me. This will be very helpful when I (or anyone else) is able to carve out time to investigate this.

**Comment by nackjicholson** [comment]
@seandstewart Hey there! I know it's been a long wait on this one. I gave it a go on PR #62. If you're able to take a look through it that would be amazing. I know you're someone who is actively using this library still and it would be extremely helpful if you could help me sanity check that I haven't broken anything obvious while fixing this bug.

This has been open a little under a year, so please don't feel any rush. Let me know if you're able.

**Comment by seandstewart** [comment]
Hey @nackjicholson -

I'll check it out this week! Thanks for getting to it 👍
