### ISSUE TITLE
[QUESTION] SQL Statements with Dynamic Filtering

### ISSUE THREAD

**Issue by MrGiga** [nackjicholson/aiosql#52]
First off sorry if this is covered somewhere. I check the docs, through the source and couldn't find anything that stood out.

How are you guys handling a sql query where you can filter on any, all or no columns in the table? Are you writing multiple sql queries of all variation?

For example you have a Users table with id, username, first_name, and last_name. Now you want to query that table by filtering on any, none or all of the other columns so you end up with:
```
Select * from users;
select * from users where id = :id
select * from users where id = id or first_name like :first_name
select * from users where id = :id or first_name like :first_name
select * from users where id = :id or first_name like :first_name or last_name like :last_name 
```

How do you achieve this without writing endless queries?

I am trying to implement a grid that allows me to filter the data.

**Comment by MrGiga** [comment]
For those who come across this question in terms of being able to add repetitive sql extensions such as "Limit" and "ORDER BY", I wrote a QueryLoader extension and that works for those scenarios.

When it comes to the ability to filter on each every column, it gets kind of complex and I have not come up with a proper solution for this.

**Comment by nackjicholson** [comment]
I think you have a very good case here where `aiosql` falls short. You're probably better off using a query builder. Something like [SQL Alchemy](https://docs.sqlalchemy.org/en/14/orm/loading_objects.html).
