### ISSUE TITLE
return cursor.rowcount from dml methods

### ISSUE THREAD

**Issue by njesp** [nackjicholson/aiosql#53]
I miss a feature to have a method return the cursor.rowcount of the dml executed inside the method

For instance

**SQL**

-- name: bulk_ins!
insert into big_t (a, b, c, d)
select a, b, c, d
from other_big_t;

**Python**

count = queries.bulk_ins(conn)

I can work around it using the .sql methods, but this would be much more elegant. 

Thank you 

Niels Jespersen

**Comment by zx80** [comment]
Done in 0b8fbda8.
