### ISSUE TITLE
Type annotations not available to users

### ISSUE THREAD

**Issue by duijf** [nackjicholson/aiosql#54]
`aiosql` does not make it's type annotations available to packages that import it. This causes `mypy` to complain about missing library stubs.

Here is a minimal way to reproduce:

```
$ mkdir reproduce && cd reproduce
$ python -m venv .env
$ source .env/bin/activate
$ cat > requirements.txt <<EOF
aiosql==3.2.0
mypy
EOF
$ pip install -r requirements.txt
$ cat > test.py <<EOF
import aiosql
EOF
$ mypy --strict test.py
test.py:1: error: Skipping analyzing 'aiosql': found module but no type hints or library stubs
test.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

This can be fixed by ensuring a `py.typed` file is available in the final environment:

```
# Continuing from above (replace with your Python version)
$ touch .env/lib/python3.9/site-packages/aiosql/py.typed
$ mypy --strict test.py
Success: no issues found in 1 source file
```

As a workaround, users can add a `type: ignore` comment on the `import aiosql` lines. However this doesn't seem ideal since `aiosql` does seem to include type annotations for most things. It would be nice if users could benefit from them without needing to create their own stubs.

I am not too familiar with Poetry, so I'm not sure whether there is an easy way to include this in wheels, etc. I would be happy to investigate / send a PR though. Let me know!

**Comment by dlax** [comment]
Simply adding `py.typed` file seems to work:
```console
$ touch aiosql/py.typed
$ poetry build
Building aiosql (3.2.0)
 - Building sdist
 - Built aiosql-3.2.0.tar.gz

 - Building wheel
 - Built aiosql-3.2.0-py3-none-any.whl
$ tar tf dist/aiosql-3.2.0.tar.gz
aiosql-3.2.0/LICENSE
aiosql-3.2.0/README.md
aiosql-3.2.0/aiosql/__init__.py
aiosql-3.2.0/aiosql/adapters/__init__.py
aiosql-3.2.0/aiosql/adapters/aiosqlite.py
aiosql-3.2.0/aiosql/adapters/asyncpg.py
aiosql-3.2.0/aiosql/adapters/psycopg2.py
aiosql-3.2.0/aiosql/adapters/sqlite3.py
aiosql-3.2.0/aiosql/aioctxlib.py
aiosql-3.2.0/aiosql/aiosql.py
aiosql-3.2.0/aiosql/exceptions.py
aiosql-3.2.0/aiosql/patterns.py
aiosql-3.2.0/aiosql/py.typed
aiosql-3.2.0/aiosql/queries.py
aiosql-3.2.0/aiosql/query_loader.py
aiosql-3.2.0/aiosql/types.py
aiosql-3.2.0/pyproject.toml
aiosql-3.2.0/setup.py
aiosql-3.2.0/PKG-INFO
```
(The file is also installed.)

**Comment by duijf** [comment]
Ah right, thanks!

I tried something like this myself, but just pointed `pip` to my fork [here](https://github.com/duijf/aiosql/commit/7d69c0631543dea9415dc9189dc0e5007ce222ab) with:

```
# requirements.txt
git+git://github.com/duijf/aiosql@7d69c0631543dea9415dc9189dc0e5007ce222ab
mypy
```

Which did not work because you cannot install `aiosql` from a git repo directly because it's use of poetry.

Type annotations are propagated correctly when I use `poetry build` to build locally and source it with:

```
# requirements.txt
# Alternatively, use the .tar.gz. It also works.
../aiosql/dist/aiosql-3.2.0-py3-none-any.whl
mypy
````

I'll open a PR :)
