### ISSUE TITLE
How can I get the actual executed sql statement.

### ISSUE THREAD

**Issue by isshe** [nackjicholson/aiosql#56]
Hello, 
How can I get the actual executed SQL statement?
My SQL is wrong, so I want to know what the SQL I actually executed.

Thanks.

**Comment by nackjicholson** [comment]
Each method has a `.sql` property. Here ya go https://nackjicholson.github.io/aiosql/advanced-topics/#accessing-prepared-sql-as-a-string


```python
print(queries.my_method.sql)
```
