### ISSUE TITLE
Would be useful to support psql style variable substitution in the # Execute Scripts operator

### ISSUE THREAD

**Issue by elgow** [nackjicholson/aiosql#58]
The psql utility provides very basic variable substitution. The ability to use psql scripts from aiosql would be very useful. The main draw would be using Python to handle CLI arguments. The variable substitution in psql is very hard to use for optional args, default args, etc. It can be done, but it requires a lot of cryptic SQL code.

**Comment by cboden** [comment]
+1


I had previous .sql scripts that looked like `SELECT * FROM users WHERE user_id = :'user_id'` which can be run in psql with setting `\set user_id 'my-1234-uuid'` first, but if I run that query in aiosql I get the following error:

> SyntaxError: syntax error at or near ":"

It would be nice if psql and aiosql queries could be compatible.

**Comment by zx80** [comment]
> The psql utility provides very basic variable substitution. The ability to use psql scripts from aiosql would be very useful. The main draw would be using Python to handle CLI arguments. The variable substitution in psql is very hard to use for optional args, default args, etc. It can be done, but it requires a lot of cryptic SQL code.

The `aiosql` interface is build over the database drivers which comply with Python DB API, so it is restricted to the abilities provided by these drivers. The `psycopg` driver is built over the `libpq` binary library, as`psql`. However has its own *language* handling feature for :-variable substitution and backslash commands, which is quite different from DB API specification and would be cumbersome to re-implement and possibly incompatible, in particular ' and " special quote handling done by `psql`. So I cannot see psql-feature making it simply into `aiosql`. Note that somehow the only really missing feature I see is mostly `:"var"` identifier quoting stuff. I'll keep it in mind nevertheless.

**Comment by zx80** [comment]
> I had previous .sql scripts that looked like `SELECT * FROM users WHERE user_id = :'user_id'` which can be run in psql with setting `\set user_id 'my-1234-uuid'` first, but if I run that query in aiosql I get the following error:
> 
> > SyntaxError: syntax error at or near ":"

Sure. Just write `SELECT sg FROM sw WHERE x = :var`, quoting is handled automatically by the underlying driver. (Note that AFAIK there is no actual quoting, the variable values are passed separately as text parameters).
