### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by clausjuhl** [nackjicholson/aiosql#59]
Hi!

Tag: Question

This is precisely the way I would like to work with db's from my python code, and I would love to use this library! However, is it in any way being maintained by the author or anyone else? There are more than one "To do"-section in the documentation, but the last commit was almost a year ago? Thanks!

**Comment by nackjicholson** [comment]
Well, I spent a lot of time making the library work as well as it does. I spent a lot of time writing the documentation that does exist. Those todo sections are there for anyone who wants to help. Sometimes I think about taking some time to write more code for you, but I'm about to have two kids under two years old, I work for an early stage startup, and I'm a bit tired from all the changes we wen through with this global pandemic thing.

**Comment by nackjicholson** [comment]
https://github.com/mcfunley/pugsql Try that one. Commits to the docs folder in the last four months.

The license is BSD, so as long as you follow the copy instructions you can make your own version of this library, do whatever you like with it and use it or redistribute it. In fact, that's exactly how I formed this project from someone else's prior work https://github.com/honza/anosql
