### ISSUE TITLE
Creating database and tables ?

### ISSUE THREAD

**Issue by asmodehn** [nackjicholson/aiosql#6]
I have been meaning to give aiosql a try, the use of sql files, along with the mapping to dataclasses as domain objects, make it attractive for my usecase.

However not having much of a SQL background, and just wanting to "store my python dataclasses into a db for recovery later on", I miss the "database/tables creation part" in aiosql...

Maybe it is just a matter of documentation more than actual features missing ?
Any Hint about that ?

Thanks a lot !

**Comment by nackjicholson** [comment]
If you'd like to make tables in your database you can write SQL to do that. You're correct, that is not a feature of aiosql.

Here is some postgres documentation about how to create tables with SQL.
https://www.postgresql.org/docs/12/sql-createtable.html

If you want to execute that from python for any reason you can use this feature of aiosql for executing sql "scripts".
https://nackjicholson.github.io/aiosql/defining_queries.html#execute-sql-script-statements-with

**Comment by asmodehn** [comment]
Yes I realized that... I m looking for some way to store my python dataclass models on disk... maybe I ll write something to generate the sql code for it from python definition eventually ;-)
For now, I ll play around with tinydb.
Anyway thanks for the info.
