### ISSUE TITLE
Driver adapter for pymssql

### ISSUE THREAD

**Issue by abbazs** [nackjicholson/aiosql#71]
I wanted to implement a driver adapter for [pymssql](https://github.com/pymssql/pymssql). I cloned the repository and did the following:

1. Copied [psycopg2.py](https://github.com/nackjicholson/aiosql/blob/master/aiosql/adapters/psycopg2.py) and renamed it as pymssql.py
2. Then added it to adapters dict in aiosql.py
```
_ADAPTERS: Dict[str, Callable[..., DriverAdapterProtocol]] = {
    "aiosqlite": AioSQLiteAdapter,
    "asyncpg": AsyncPGAdapter,
    "psycopg2": PsycoPG2Adapter,
    "sqlite3": SQLite3DriverAdapter,
    "pymssql": PymssqlAdapter,
}
```
3. Build the project as a wheel
4. Installed it in a project environment

It simply worked what am I missing? Is it so simple to build adapters?

**Comment by nackjicholson** [comment]
Lol, maybe. If psycopg2 and pymssql conform to the same exact interface. You might run into some edge cases. Try it out for awhile and let us know! Thanks for posting an issue to surface it, could be useful for others trying to do the same thing.

**Comment by nackjicholson** [comment]
I think #88 will add this officially to the project. But it's not a done deal yet.

**Comment by zx80** [comment]
About #88: indeed adding "pymssql" could be added if the Postgres adapters work directly.

If `aiosql` follows this path, maybe someone should check whether Oracle could work, eg with `cx_oracle`?

Copying the adapter class is not needed, refactoring is a better software engineering approach to avoid duplicating code.

I cannot test a MS SQL or Oracle server setup, and do not plan to do that *ever*.
