### ISSUE TITLE
Postgres -> INSERT INTO

### ISSUE THREAD

**Issue by rlitchfield-Edcara** [nackjicholson/aiosql#72]
I've run into an interesting issue.  When I attempt to do a INSERT INTO using Postgres, it does not save the actual record, however it does increase the sequence by one.  When I do a RETURNING on the id, I see the new id, and that matches with the sequences on the actual database.  However, the record is never saved.

UPDATE and SELECT work fine, so I know the connection to the database is working.

Any idea on what might be the issue?  Is there a way I could see any errors that are occurring in the aiosql that are not displayed automatically?

Other than this issue (which is obviously important) this is an amazing addition to my project, so thank you for all the work you've done on it.

UPDATE....
I've done some more testing and something even stranger is occurring.  Does the code create a temporary DB in memory?  What is happening is that once I create the new record, I am able to do a SELECT in my web application and the record displays. (Using PGAdmin, I can not see the record in the DB.)   However, when I stop the app and start it again, the record is gone.  The above still happens, while the record is not saved, the sequence number does increment by one in the DB.

**Comment by rlitchfield-Edcara** [comment]
I've been able to "solve" this by adding conn.autocommit = True.  I have not been able to find anything in the documentation that would suggest this is required.

**Comment by nackjicholson** [comment]
Hi @rlitchfield-Edcara, if you're using psycopg2 this is a common source of confusion. So much so that it's their first FAQ.

https://www.psycopg.org/docs/faq.html#problems-with-transactions-handling

Also, read this section in depth.

https://www.psycopg.org/docs/usage.html#transactions-control

Glad you figured it out.

Best,
Will
