### ISSUE TITLE
Pip install aiosql does not install py.typed

### ISSUE THREAD

**Issue by sylvainmouquet** [nackjicholson/aiosql#73]
Hello,

When i compare my current install and the last release i have not the file py.typed
Could you add it ?

Thanks

**Comment by nackjicholson** [comment]
@sylvainmouquet Hmmmm, I don't know how that happened. It is here in the repository. I'll look into it. Thank you for letting me know.

**Comment by nackjicholson** [comment]
I think this has been fixed.
