### ISSUE TITLE
Alternatives to `record_classes`?

### ISSUE THREAD

**Issue by waydegg** [nackjicholson/aiosql#77]
After reading some of @nackjicholson 's comments in a few issues about how using `record_classes` was a bad idea to begin with (and is now deprecated), I'm curious as to what people are doing instead for converting raw records into other objects? For reference, my use cases mainly involve converting records into Pydantic models or Pandas dataframes/series.

**Comment by alexcohaniuc** [comment]
I'm curious about this as well. any ideas?

**Comment by nackjicholson** [comment]
It's not that it's a bad idea. It's that it was something I shouldn't have done in aiosql. I think aiosql is simpler if it deals in raw python types, but I'm all for someone layering something on top of aiosql somehow to marshal results.

**Comment by zx80** [comment]
No action to take.
