### ISSUE TITLE
aiosql-mysql: sync and async mysql driver adaptor library

### ISSUE THREAD

**Issue by kajuberdut** [nackjicholson/aiosql#79]
Hello,

I think this library is very neat and I wanted to provide async and sync MySQL adaptors.

After reading through issues #24, #44 I have created: [aiosql-mysql](https://github.com/kajuberdut/aiosql-mysql).

This is still pretty rough, the sync version with PyMySQL is working but the async version is not. After I have a working async function I will publish this to PyPI and add installation instructions.

I am interested in any feedback.

**Comment by kajuberdut** [comment]
There is a pre-release version on PyPI if anybody wants to give it a go: https://pypi.org/project/aiosql-mysql/0.0.1a1/

**Comment by zx80** [comment]
Thanks for the link. I'm planning to add some MySQL adapters, not only PyMySQL, see GH-88.
