### ISSUE TITLE
asyncpg execute return is not passed

### ISSUE THREAD

**Issue by euri10** [nackjicholson/aiosql#8]
greetings, amazing library I'm discovering so bear with me maybe I'm misusing it.

should I use asyncpg directly this way, the response will be `CREATE DATABASE`

```
dbpool = await get_db_pool(database_subscriber_dsn)
# response = await create_queries.create_db_test(dbpool)
response = await dbpool.execute("create database postgres_test;")
```
now should I try it with aiosql with the following sql file it returns None
```
-- name: create_db_test#
create database postgres_test;
```

happy to send a little PR

**Comment by nackjicholson** [comment]
What is on the response object that you need? None of the adapters return from `execute_script`. I think my assumption was that if you're defining a script, you just want it to run and you don't need anything back.

**Comment by euri10** [comment]
I'm creating database, schema, and copy_to_table I'm used to postgesql letting me know it was successful with stuff like this for instance
```
dsn: PostgresDsn = get_app_settings().dsn
    conn = await asyncpg.connect(dsn)
    response = await conn.execute("create database postgres_test;")
    await conn.close()
    assert response == "CREATE DATABASE"
```

**Comment by nackjicholson** [comment]
@euri10 Hey thanks for the info. Sorry it's been so long since I've been able to come back and look at this project. I'm hoping to review this soon. Need to put it on my TODO list :)

Thank you so much for taking the time to help identify this improvement.

**Comment by nackjicholson** [comment]
For psycopg2 this would use: https://www.psycopg.org/docs/cursor.html#cursor.statusmessage

Not sure it has an analog for the sqlite3 drivers.

**Comment by nackjicholson** [comment]
It does not have an analog for sqlite drivers unfortunately. But I am just returning a string "DONE" for those drivers. This is done @euri10
