### ISSUE TITLE
psycopg 3 support?

### ISSUE THREAD

**Issue by zx80** [nackjicholson/aiosql#80]
Any plan?

**Comment by nackjicholson** [comment]
I have no plan!

**Comment by zx80** [comment]
Hmmm… AFAICS it is enough to just reuse the `psycopg2` adapter, so a one-liner is probably enough.

```
     "psycopg2": PsycoPG2Adapter,
+    "psycopg": PsycoPG2Adapter,
     "sqlite3": SQLite3DriverAdapter,
```

**Comment by jorge4larcon** [comment]
Hi guys, I love this tool!

Is there any plan of adding psycopg3 support?

**Comment by zx80** [comment]
> Is there any plan of adding psycopg3 support?

Sure. WIP. The stuff is stuck on a CI issue that I have not the time to investgate right now.

**Comment by zx80** [comment]
Done!
