### ISSUE TITLE
Typing Extensions >= 4?

### ISSUE THREAD

**Issue by zx80** [nackjicholson/aiosql#81]
It seems that there is a requirement for `typing_extensions<4` which breaks pkg_resources if `typing_extensions >= 4` is installed for some other packages. Current version is *4.0.1*.

Any plan to remove this constraint or switch to the newer one?

Python is a moving target, and core packages do not aim at backward compatibility :cry:

**Comment by nackjicholson** [comment]
I'm sure we can lift that constraint and move to the new version. But I don't know when I'll do it.

**Comment by Pentusha** [comment]
Seems like broken since pytest 7.1.3+ see: https://github.com/nsidnev/edgeql-queries/actions/runs/3164485222/jobs/5152803541
```python
ModuleNotFoundError: No module named 'pkg_resources'
```
AFAIK it should be replaced with importlib_metadata

**Comment by zx80** [comment]
I added a dependency on `setuptools` so that `pkg_resources` should be available.

Once python 3.7 is out (June 2023) I will switch to `importlib.metadata`.

**Comment by zx80** [comment]
See v6.5

**Comment by Pentusha** [comment]
Still not working for me.
```
(edgeql-queries-W3JrN5fl-py3.9) ➜  edgeql-queries git:(master) ✗ poetry run pip freeze | grep aiosql  
aiosql @ file:///home/pentusha/.cache/pypoetry/artifacts/7c/7f/cb/6c266cfa5ed9147e1f6b9959509a6e953fe8057dd18863e3489339d374/aiosql-6.5-py3-none-any.whl
```

```
../../.cache/pypoetry/virtualenvs/edgeql-queries-W3JrN5fl-py3.9/lib/python3.9/site-packages/aiosql/__init__.py:7: in <module>
    import pkg_resources as pkg  # type: ignore
E   ModuleNotFoundError: No module named 'pkg_resources'
```
