### ISSUE TITLE
What is difference in comparsion to just move SQL queries to "sqls" file?

### ISSUE THREAD

**Issue by david-shiko** [nackjicholson/aiosql#95]
What is the difference in comparison to just moving SQL queries to "sqls" file?
The only difference that I see is handy way to execute queries:
Instead of 
```
cur.execute(sql)
cur.fetchall()
```

We can write one line less: ` queries.get_all_users(conn)`

**Comment by nackjicholson** [comment]
@david-shiko I'm sorry, I don't understand your question or the comparison you're making.
