### ISSUE TITLE
Are there plans to add AIomysQL support

### ISSUE THREAD

**Issue by Mankvis** [nackjicholson/aiosql#99]
hi, Are there plans to add AIomysQL support

**Comment by nackjicholson** [comment]
Hello, yeah. Our friend @zx80 Fabien has done some work toward it https://github.com/nackjicholson/aiosql/pull/88

**Comment by zx80** [comment]
Yep. I'll try to give a go at the async adapters as well.

**Comment by houyingkun** [comment]
> Yep. I'll try to give a go at the async adapters as well.

Haven't seen the support for aiomysql yet. Are there any plans to support it in the future?

**Comment by zx80** [comment]
There are no plans *NOT* to do it, PR are welcome!
